"""Markdown import persistence for Tingji's text-only entry point.

Reuses Tingji's meeting-directory/meta helpers; no parallel database or audio
pipeline. Original bytes are immutable. All offsets are UTF-16 code units, so
browser String.slice and source highlights use the same coordinates.
"""
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile
from datetime import datetime, timezone

from app import storage

MAX_SOURCE_BYTES = 1024 * 1024
VALID_ID = re.compile(r'[a-f0-9]{32}')


class TextError(Exception):
    def __init__(self, code, message, status=400):
        self.code, self.message, self.status = code, message, status
        super().__init__(message)


def validate_source(filename, content, title):
    if not filename or len(filename) > 255 or any(c in filename for c in '/\\\x00') or Path(filename).suffix.lower() != '.md':
        raise TextError('INVALID_FILE', '请选择 .md 文件，不支持音频或其他格式。', 415)
    if len(content) > MAX_SOURCE_BYTES:
        raise TextError('FILE_TOO_LARGE', '文件超过 1 MB，请先确认文件内容。', 413)
    try:
        text = content.decode('utf-8-sig')
    except UnicodeDecodeError:
        raise TextError('INVALID_ENCODING', '文件不是 UTF-8 编码，请另存为 UTF-8 Markdown。') from None
    if len(text.splitlines()) > 20_000:
        raise TextError('TOO_MANY_LINES', '文件超过 20,000 行，请确认这是一小时以内的会议稿。', 413)
    if not text.strip():
        raise TextError('EMPTY_FILE', '文件内容为空，请重新选择。')
    if any(ord(c) < 32 and c not in '\t\r\n' for c in text):
        raise TextError('INVALID_FILE', '文件含有非文本内容，不能作为会议稿导入。')
    title = title.strip() or Path(filename).stem
    if len(title) > 120 or any(ord(c) < 32 for c in title):
        raise TextError('INVALID_TITLE', '会议标题应为 1–120 个字符，不能含控制字符。')
    return text, title


def source_index(meeting_id, text, digest):
    offset, segments = 0, []
    for line_no, line in enumerate(text.splitlines(keepends=True), 1):
        width = len(line.encode('utf-16-le')) // 2
        segments.append({'segment_id': f'{meeting_id}:L{line_no}', 'line': line_no,
                         'start_utf16': offset, 'end_utf16': offset + width})
        offset += width
    return {'schema_version': 1, 'source_id': meeting_id, 'sha256': digest,
            'coordinate_system': 'utf16', 'segments': segments}


def _owner_dir(owner):
    if not owner or len(owner) > 128:
        raise TextError('UNAUTHORIZED', '身份无效。', 401)
    return storage.get_data_dir() / 'users' / hashlib.sha256(owner.encode()).hexdigest()


def meeting_dir(owner, meeting_id):
    if not VALID_ID.fullmatch(meeting_id or ''):
        raise TextError('NOT_FOUND', '找不到这场会议。', 404)
    path = _owner_dir(owner) / meeting_id
    if path.is_symlink():
        raise TextError('NOT_FOUND', '找不到这场会议。', 404)
    return path


def _write_bytes(path, content):
    with open(path, 'xb') as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())


def import_markdown(owner, meeting_id, filename, content, title):
    text, title = validate_source(filename, content, title)
    dest = meeting_dir(owner, meeting_id)
    root = dest.parent
    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    digest = hashlib.sha256(content).hexdigest()
    fingerprint = hashlib.sha256(json.dumps([digest, filename, title], ensure_ascii=False).encode()).hexdigest()
    # Independent open descriptions: serializes threads AND processes on this owner.
    with open(root / '.import.lock', 'a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if dest.exists():
            prior = get_meeting(owner, meeting_id)
            if prior['meta'].get('import_fingerprint') != fingerprint:
                raise TextError('IMPORT_CONFLICT', '此次导入已保存，但内容不同。请重新选择文件。', 409)
            return prior['meta'], False
        stage = Path(tempfile.mkdtemp(prefix='.import-', dir=root))
        try:
            index = source_index(meeting_id, text, digest)
            meta = {'id': meeting_id, 'title': title, 'created_at': datetime.now(timezone.utc).isoformat(),
                    'status': 'draft', 'source': 'markdown', 'filename': filename, 'source_sha256': digest,
                    'source_bytes': len(content), 'line_count': len(index['segments']),
                    'import_fingerprint': fingerprint, 'tags': [], 'error': None, 'schema_version': 1}
            _write_bytes(stage / 'original.md', content)
            os.chmod(stage / 'original.md', 0o444)
            _write_bytes(stage / 'source-index.json', json.dumps(index, ensure_ascii=False).encode())
            storage._write_meta(stage, meta)
            # Sync metadata generated by upstream helper, then atomically publish.
            with open(stage / 'meta.json', 'rb') as f:
                os.fsync(f.fileno())
            os.rename(stage, dest)
            fd = os.open(root, os.O_RDONLY)
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
        except Exception:
            if stage.exists():
                shutil.rmtree(stage)
            raise
    return meta, True


def get_meeting(owner, meeting_id):
    path = meeting_dir(owner, meeting_id)
    if not path.is_dir():
        raise TextError('NOT_FOUND', '找不到这场会议。', 404)
    meta = storage._read_meta(path)
    if not isinstance(meta, dict) or meta.get('id') != meeting_id or not all(
        isinstance(meta.get(key), str) for key in ('title', 'filename', 'created_at', 'source_sha256', 'import_fingerprint')
    ):
        raise TextError('STORAGE_CORRUPT', '会议记录损坏，请勿继续处理。', 409)
    try:
        content = (path / 'original.md').read_bytes()
        if hashlib.sha256(content).hexdigest() != meta['source_sha256']:
            raise TextError('SOURCE_CHANGED', '原始文件发生变化，已停止读取。', 409)
        text = content.decode('utf-8-sig')
        index = json.loads((path / 'source-index.json').read_text())
        if index != source_index(meeting_id, text, meta['source_sha256']):
            raise TextError('INDEX_CHANGED', '原文索引发生变化，已停止读取。', 409)
    except (OSError, ValueError, KeyError):
        raise TextError('STORAGE_CORRUPT', '会议文件不完整，请勿继续处理。', 409) from None
    return {'meta': meta, 'source_text': text, 'source_index': index,
            'processed': None, 'summary': None, 'summary_json': None}


def set_archived(owner, meeting_id, archived):
    """Hide or show a meeting in the default list. Nothing is deleted; only the meta tag changes."""
    if not isinstance(archived, bool): raise TextError('INVALID_REQUEST', '归档请求格式无效。')
    path = meeting_dir(owner, meeting_id)
    get_meeting(owner, meeting_id)  # NOT_FOUND for other owners before touching any lock
    with open(path.parent / '.import.lock', 'a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        meta = get_meeting(owner, meeting_id)['meta']
        tags = [t for t in meta.get('tags', []) if t != 'archived'] + (['archived'] if archived else [])
        meta['tags'] = tags
        storage._write_meta(path, meta)
    return {'id': meeting_id, 'archived': archived}


def list_meetings(owner, tolerate_corrupt=False):
    root = _owner_dir(owner)
    if not root.exists():
        return []
    items = []
    for path in root.iterdir():
        if path.is_dir() and VALID_ID.fullmatch(path.name):
            # A broken meeting stays visible without blocking unrelated meetings.
            try:
                items.append(get_meeting(owner, path.name)['meta'])
            except TextError as exc:
                if not tolerate_corrupt: raise
                items.append({'id': path.name, 'title': '会议文件校验失败', 'created_at': '',
                              'status': 'failed', 'line_count': 0, 'tags': [],
                              'error': {'code': exc.code, 'message': exc.message}})
    return sorted(items, key=lambda m: (m['created_at'], m['id']), reverse=True)
